[package]
name = "rust_animation"
version = "0.1.0"
authors = ["joao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slice-fill = "1.0.1"
image = "0.22.0"


